spring:
  application:
    name: @pom.artifactId@
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

info:
  app:
    name: @pom.artifactId@

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream