spring:
  application:
    name: @pom.artifactId@
server:
  port: 8002
  servlet:
    context-path: /@pom.artifactId@

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/